/* This file was automatically generated.  Do not edit! */
int strcmp(const char *s1,const char *s2);
int sprintf(char *str,const char *fmt,...);
int vprintf(const char *fmt,va_list ap);
int printf(const char *fmt,...);
int putchar(int c);
char *strcpy(char *dest,const char *src);
time_t mktime(struct tm *tm);
int __vfprintf_chk(FILE *__restrict __stream,int __flag,const char *__restrict __format,_G_va_list __ap);
int __printf_chk(int __flag,const char *__restrict __format,...);
int open(const char *path,int flags,...);
int __open_2(const char *path,int mode);
const char *strstr(const char *haystack,const char *needle);
int rand();
int puts(const char *s);
size_t fread(void *ptr,size_t size,size_t nmemb,FILE *stream);
long ftell(FILE *stream);
int fseek(FILE *stream,long offset,int whence);
int fclose(FILE *f);
extern FILE *stderr;
int close(int fd);
FILE *fopen(const char *path,const char *mode);
void *mremap(void *old_address,size_t old_size,size_t new_size,int flags,void *new_address);
int memcmp(const void *_s1,const void *_s2,size_t n);
void memset(void *s,int c,size_t n);
ssize_t write(int fd,const void *ptr,size_t count);
ssize_t read(int fd,void *ptr,size_t count);
int munmap(void *addr,size_t length);
void *mmap(void *addr,size_t length,int prot,int flags,int fd,off_t offset);
long int __fdelt_chk(long int d);
void *__memcpy_chk(char *dest,char *src,size_t len,size_t dstlen);
uint8_t *memcpy(uint8_t *dest,const uint8_t *src,size_t n);
size_t strlen(const char *s);
void *__strcpy_chk(char *dest,char *src,size_t dstlen);
void __chk_fail();
void abort();
int *__errno_location();
extern int errno;
time_t time(time_t *t);
int select(int __nfds,fd_set *__restrict __readfds,fd_set *__restrict __writefds,fd_set *__restrict __exceptfds,struct timeval *__restrict __timeout);
int fcntl(int fd,int cmd,...);
